### PR TITLE
macOS Big Sur additional step to README.md

### PR DESCRIPTION
**Pull request by ludufre**
Hi,

I'm on macOS Big Sur 11.1 (20C69) fresh install and I can only install with those additional steps.

### CODE REVIEW

**Comment by supersaiyanmode** [comment]
The dependency of `cryptography` should already be there in `requirements.txt` via `requests[security]`. You can verify from [here](https://github.com/supersaiyanmode/PyWebOSTV/network/dependencies) (under psf/requests).

At this point I am inclined to think that it is just your machine and the way it is set up. Can you confirm if you see similar behavior in an freshly create virtuanenv? Can someone else on Big Sur please confirm?

**Comment by ludufre** [comment]
Same behavior on my iMac 2019 and Macbook Pro 2014 with 11.1 (20C69). Fresh install (today), Xcode downloaded from App Store.

But, we can see if anyone else had this problem ...

**Comment by ludufre** [comment]
Just to be clear, the original error was: `'openssl/opensslv.h' file not found`

**Comment by supersaiyanmode** [comment]
I think I understand what is going on from your error. Would you be okay to rephrase the messaging as below?

> If you see errors such as openssl file not found, it most likely indicates that you don't have a working installation of OpenSSL. In such a case, we would recommend that you install it using the following steps (assuming you've brew as your package manager):
> [step1]
> [step2]
> ..
>

**Comment by ludufre** [comment]
Of course! No problems. I submitted a new commit. See if it's okay.

**Review by supersaiyanmode — APPROVED** [review]

**Comment by supersaiyanmode** [comment]
Thanks so much @ludufre for this PR :)

**Pull request merged**
